/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataproject;

import java.awt.Color;
import java.awt.Image;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author veranur
 */
public class frm_game extends javax.swing.JFrame {

    /**
     * Creates new form FrmGame
     */
    static String username;
    static int level;
    Node head;
    final int cellCount = 32;
    Node currentPlayer;
    int score = 0;
    public static ImageIcon iconPlayer= new ImageIcon("assets/player.png");
    public frm_game(String username, int level) {
        initComponents();
        this.username = username;
        this.level = level;
        labelUsername.setText("Kullanıcı Ad: " + username + "  Level: " +level);
        randomCreateLinkedList(jPanel1);
        
    }
    
    private void randomCreateLinkedList(JPanel panel) {
        Random random = new Random();
        head = new Node(0, randomType(random));
        panel.add(head.button);
        setPosition(head.button, 0);

        Node current = head;
        for (int i = 1; i < cellCount; i++) {
            Node newNode = new Node(i, randomType(random));
            current.next = newNode;
            current = newNode;

            panel.add(current.button);
            setPosition(current.button, i);
        }
        currentPlayer = head;
        showCurrentPlayer(currentPlayer);
    }
    
    private String randomType(Random rand) {
        int r = rand.nextInt(100);
        if (r < 40) return "treasure";    
        else if (r < 65) return "trap";    
        else return "empty";               
    }
    //buraya şey de yapabiliriz 1'den 3e kadar random sayı tutarız sonra her seferinde farklı sayı geleceği için 
    // 1 2 3 e göre hazine tuzak veya boş olarak döndürebiliriz?? 

    private void setPosition(JButton btn, int i) {
        int x = 60 + (i % 10) * 90;
        int y = 60 + (i / 10) * 90;
        btn.setLocation(x, y);
    }
    //bu fonksiyon butonların boyutuna göre aralarında 10 şey bırakıp yan yana dizmek için ve max 10 tane diziyor bi sıraya baştan da 60 boşluk bırakıyor
    
    private void updateScore(String type){
        switch (type) {
        case "treasure":
            score += 10;
            break;
        case "trap":
            score -= 5;
            break;
        }
        labelScore.setText("Skor: " + score);
    }
    private void showCurrentPlayer(Node node){
        node.button.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        Image img1 = iconPlayer.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        iconPlayer = new ImageIcon(img1);
        node.button.setText(null);
        node.button.setIcon(iconPlayer); //buraya ikon ekleyelim bence hoş olabilir. 
    }
    
    private void dontShowCurrentPlayer(Node node){
        if (node != null) {
        node.updateButton();
        }
    }
    private void endGame(){
        try {
            FileWriter write=new FileWriter("score.txt", true);
            write.write(username +" , level "+ level +", " + score + "\n");
            write.close();
        } catch (IOException ex) {
            Logger.getLogger(frm_game.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int option= JOptionPane.showConfirmDialog(this, "Congratulations \nYour Score: " + score + "\n Would you like to continue to the next level?", "Game Over", JOptionPane.YES_NO_OPTION);
        if (option==JOptionPane.YES_NO_OPTION && level==1) {
            this.dispose();
            new frm_game(username, 2).setVisible(true);
            //ikinci kısım için nasıl yapacağımızı düşünüp ona göre burası revize edilmeli
        }else{
            this.dispose();
            new frm_menu().setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        dice = new javax.swing.JButton();
        labelScore = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        dice.setText("🎲 Zar At");
        dice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceActionPerformed(evt);
            }
        });

        labelScore.setText("Score: 0");
        labelScore.setAlignmentY(0.0F);

        labelUsername.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(dice, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelScore, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(443, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addComponent(back)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new frm_menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void diceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceActionPerformed
       Random random = new Random();
       int rolls=random.nextInt(6)+1;
       JOptionPane.showMessageDialog(this, "Zar sonucu: "+rolls);
       
        dontShowCurrentPlayer(currentPlayer);
       
        for (int i = 0; i < rolls; i++) {
            if (currentPlayer.next!= null) {
                currentPlayer=currentPlayer.next;
            }else{
                break;
            }
        }
        showCurrentPlayer(currentPlayer);
        updateScore(currentPlayer.type);
        if (currentPlayer.next==null) {
           endGame();
        }
        
    }//GEN-LAST:event_diceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_game(username,level).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton dice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelScore;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
